/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 15/10/2010, 14:23:01
 */
package telas;

import beans.Item;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import processos.*;

/**
 *teste
 * @author zerokol
 */
public class Principal extends javax.swing.JFrame implements Runnable {

    private final int tamanho = 8;
    JTable jt = new JTable();
    ArrayList<Item> buffer = new ArrayList<Item>();
    Produtor prod = new Produtor("produtor", buffer);
    Consumidor cons = new Consumidor("consumidor", buffer);
    Imprimir imp = new Imprimir("Imprimir", buffer, jt);
    //Imprimir imp = new Imprimir("Imprimir", buffer);
    Item it = new Item();

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        jt = jTable1;
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        estadoProd = new javax.swing.JLabel();
        estadoCons = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ultimaAcao = new javax.swing.JLabel();
        slideProd = new javax.swing.JSlider();
        slideCons = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problema do Produtor\\Consumidor");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Item 1");
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Item 2");
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Item 3");
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Item 4");
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setHeaderValue("Item 5");
        jTable1.getColumnModel().getColumn(5).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Item 6");
        jTable1.getColumnModel().getColumn(6).setResizable(false);
        jTable1.getColumnModel().getColumn(6).setHeaderValue("Item 7");
        jTable1.getColumnModel().getColumn(7).setResizable(false);
        jTable1.getColumnModel().getColumn(7).setHeaderValue("Item 8");

        jLabel1.setText("<html>Estado do <b>Consumidor</b>: </html>");

        jLabel2.setText("<html> Estado do <b>Produtor</b>:</html>");

        estadoProd.setText("Ativo");

        estadoCons.setText("Ativo");

        jLabel5.setText("Última ação:");

        ultimaAcao.setForeground(new java.awt.Color(255, 4, 20));
        ultimaAcao.setText("última ação");
        ultimaAcao.setMaximumSize(new java.awt.Dimension(300, 15));

        slideProd.setInverted(true);
        slideProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slideProdMouseReleased(evt);
            }
        });

        slideCons.setInverted(true);
        slideCons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slideConsMouseReleased(evt);
            }
        });

        jLabel3.setText("Velocidade do Produtor:");

        jLabel4.setText("Velocidade do Consumidor:");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(estadoCons, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slideCons, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slideProd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ultimaAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoCons, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(slideProd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(slideCons, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ultimaAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
    }//GEN-LAST:event_jTable1PropertyChange

    private void slideProdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideProdMouseReleased
        prod.setVariacao((slideProd.getValue() * 0.01) * 5);
    }//GEN-LAST:event_slideProdMouseReleased

    private void slideConsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideConsMouseReleased
        cons.setVariacao((slideCons.getValue() * 0.01) * 5);
    }//GEN-LAST:event_slideConsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Thread geral = new Thread(new Principal());
        geral.setName("principal");
        geral.start();
    }

    public void run() {
        prod.start();
        cons.start();
        //imp.start();
        while (true) {
            try {
                if (buffer.size() >= tamanho) {
                    prod.setestado(true);
                    cons.setestado(false);
                    //System.out.print("\nProd em Wait e Cons Notify!\n");
                    ultimaAcao.setText("<html><b>Produtor</b> em <i>wait()</i> e <b>Consumidor</b> em <i>notify()</i>!</html>");
                    estadoProd.setText("Dormindo");
                    estadoCons.setText("Acordado");
                }

                if (prod.getState() == Thread.State.WAITING && buffer.size() == tamanho / 2) {
                    prod.setestado(false);
                    ultimaAcao.setText("<html>Acordando o <b>Produtor</b>!</html>");
                }

                if (cons.getState() == Thread.State.WAITING && buffer.size() == tamanho / 2) {
                    cons.setestado(false);
                    ultimaAcao.setText("<html>Acordando o <b>Consumidor</b>!</html>");
                    estadoCons.setText("Acordado");
                }

                if (buffer.size() == 0) {
                    cons.setestado(true);
                    prod.setestado(false);
                    //System.out.print("\nCons em Wait e Prod Notify!\n");
                    ultimaAcao.setText("<html><b>Consumidor</b> em <i>wait()</i> e <b>Produtor</b> em <i>notify()</i>!</html>");
                    estadoProd.setText("Acordado");
                    estadoCons.setText("Dormindo");
                }

                povoarTabela();
                Thread.sleep(500);

                /*prod.setestado(true);
                cons.setestado(true);
                imp.setestado(false, 1);*/
            } catch (InterruptedException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void povoarTabela() {
        int x;
        if (buffer.size() > 0) {
            for (x = 0; x < buffer.size(); x++) {
                it = buffer.get(x);
                jTable1.getModel().setValueAt(it.getNome(), 0, x);
                jTable1.setValueAt(it.getCor(), 1, x);
                jTable1.setValueAt(it.getValor(), 2, x);
            }
            while (x < tamanho) {
                jTable1.getModel().setValueAt(null, 0, x);
                jTable1.setValueAt(null, 1, x);
                jTable1.setValueAt(null, 2, x);
                x++;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estadoCons;
    private javax.swing.JLabel estadoProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSlider slideCons;
    private javax.swing.JSlider slideProd;
    private javax.swing.JLabel ultimaAcao;
    // End of variables declaration//GEN-END:variables
}
